name: Publish Package

on:
  workflow_dispatch:

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
      - uses: actions/checkout@v4
        # these if statements ensure that a publication only occurs when
        # a new release is created:
        if: ${{ steps.release.outputs.release_created }}
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
          # registry-url: 'https://npm.pkg.github.com'
          scope: '@facturacr' 
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: npm publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}