on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

name: Create Release PR please 🙏

jobs:
  release-please-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          release-type: node
          token: ${{ secrets.GITHUB_TOKEN }}